#!/usr/bin/env bash

max_image_length=30



docker container ps --format "json" |
  jq --slurp --raw-output --arg _max_len "${max_image_length}" --from-file /dev/fd/3 3<<"EOF"
    ($_max_len | tonumber) as $MAX_LEN
    | .[]
    | to_entries
    | map({
      key: .key,
      value:
      (if (.key == "Image") and ((.value | length) > $MAX_LEN)
          then "..." + .value[-$MAX_LEN:]
          else .value
        end)
      })
    | from_entries
    | [.ID, .Names]
    #| ["ID", "NAME"]
   # | sort_by(.ID)
    # | @tsv
    

EOF





# \
#   | jq --slurp '.[] | [.ID, .Names, .Status, .Image, .Ports, (.CreatedAt | split(" ") | join("_"))]' \
#   | jq --slurp '. | [["ID", "CONTAINER NAME", "STATUS", "IMAGE", "PORTS", "__CREATED_AT_ISO8601_ISH"]] + .' \
#   | jq --raw-output '.[] | @tsv' \
#   | sort --key="2" |  # Sort on "CONTAINER NAME" first \
#   | sort --key="5" --stable |  # .. then stably on "__ CREATED_AT_ISO8601_ISH" \
#   | cut -d $'\t' -f-5 |  # cut out the "__CREATED_AT_I SO8601_ISH" column
#   | column -t -s $'\t'

