#!/usr/bin/env zsh

max_image_length=30

docker container ps --format "json" |
  MAX_LEN="${max_image_length}" jq '
    (env.MAX_LEN | tonumber) as $MAX_LEN
    | to_entries
    | map({
      key: .key,
      value:
      (if (.key == "Image") and ((.value | length) > $MAX_LEN)
          then "..." + .value[-$MAX_LEN:] 
          else .value
        end)
      }) 
    | from_entries
  ' |
  jq --slurp '.[] | [.ID, .Names, .Status, .Image, .CreatedAt]' |
  jq --slurp '. | [["ID", "CONTAINER NAME", "STATUS", "IMAGE", "__CREATED_AT_ISO8601_ISH"]] + .' |
  jq --raw-output '.[] | @tsv' | 
    # Note: Columns in `sort` and `cut` are 1-indexed
  sort --key="2" |  # Sort on "CONTAINER NAME" first
  sort --key="5" --stable |  # .. then stably on "__CREATED_AT_ISO8601_ISH"
  cut -d $'\t' -f-4 |  # cut out the "__CREATED_AT_ISO8601_ISH" column
  column -t -s $'\t'
